# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.21/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
  labels:
    name: calico-system
---
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  {% if config.registry.image_pull_secret %}
  imagePullSecrets:
    - name: {{ config.registry.image_pull_secret|yaml_quote }}
  {% endif %}
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: {{ config.calico_config.net_config.block_size }}
      cidr: {{ config.net_config.pod_subnet }}
      encapsulation: {{ config.calico_config.net_config.encapsulation }}
      natOutgoing: {{ config.calico_config.net_config.nat_outgoing }}
      nodeSelector: {{ config.calico_config.net_config.nodeSelector }}
---
# This section configures the Calico API server.
# For more information, see: https://docs.projectcalico.org/v3.21/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
{% if config.aci_config.cluster_l3out.bgp.secret %}
---
#This creates a secret to store the BGP Password. We also need to add a Roleand RoleBinding to ensure the calico-node ServiceAccount can access the Secret.
apiVersion: v1
kind: Secret
metadata:
  name: bgp-secrets
  namespace: calico-system
type: Opaque
stringData:
  rr-password: {{ config.aci_config.cluster_l3out.bgp.secret }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access
  namespace: calico-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["bgp-secrets"]
  verbs: ["watch", "list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access
  namespace: calico-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-access
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: calico-system
{% endif %}
---