  aciOperatorConfig:
    flavor: {{ config.flavor|json }}
    config: {{ config.kube_config.deployment_base64|json }}

  aciConfig:
    systemId: {{ config.aci_config.system_id }}
    {% if config.user_config.aci_config.apic_hosts %}
    apicHosts": {{config.aci_config.apic_hosts|json|indent(width=16)}},
    {% endif %}
    {% if config.user_config.aci_config.aep %}
    aep: {{config.aci_config.aep|json}},
    {% endif %}
    {% if config.aci_config.apic_subscription_delay %}
    apicSubscriptionDelay: {{ config.aci_config.apic_subscription_delay|json }},
    {% endif %}
    {% if config.aci_config.apic_refreshticker_adjust %}
    apicRefreshtickerAdjust": {{ config.aci_config.apic_refreshticker_adjust|json }},
    {% endif %}
    {% if config.aci_config.opflex_device_delete_timeout %}
    opflexDeviceDeleteTimeout": {{ config.aci_config.opflex_device_delete_timeout|json }},
    {% endif %}
    {% if config.user_config.aci_config.tenant %}
     tenant:
       name: {{config.user_config.aci_config.tenant.name|json}},
     {% endif %}
     vrf:
       name: {{config.aci_config.vrf.name|json}}
       tenant: {{config.aci_config.vrf.tenant|json}}
     SyncLogin:
       username: {{ config.aci_config.sync_login.username }}
       password: {{ config.aci_config.sync_login.password }}
       keyfile:  {{ config.aci_config.sync_login.key_data|base64enc }}
       certfile: {{ config.aci_config.sync_login.cert_data|base64enc }}
     {% if config.user_config.aci_config.client_ssl %}
     clientSsl": {{ config.aci_config.client_ssl|json }},
     {% endif %}
     vmmDomain:
       type: {{ config.user_config.aci_config.vmm_domain.type }}
       encapType: {{ config.user_config.aci_config.vmm_domain.encap_type }}
       mcastFabric: {{ config.user_config.aci_config.vmm_domain.mcast_fabric }}
       mcastRange:
         start: {{ config.user_config.aci_config.vmm_domain.mcast_range.start }}
         end: {{ config.user_config.aci_config.vmm_domain.mcast_range.end }}
       nestedInside:
         type: {{ config.user_config.aci_config.vmm_domain.nested_inside.type }}
         name: {{ config.user_config.aci_config.vmm_domain.nested_inside.name }}
         installerProvisionedLbIp: {{ config.user_config.aci_config.vmm_domain.nested_inside.installer_provisioned_lb_ip }}
     l3out:
       name: {{config.aci_config.l3out.name|json}}
       externalNetworks": {{ config.aci_config.l3out.external_networks|json }}
    
  {% if config.user_config.registry %}
  registry:
    imagePrefix: {{ config.user_config.registry.image_prefix}},
    aciCniOperatorVersion: {{ config.user_config.registry.aci_cni_operator_version}},
  {% endif %}
  {% if config.user_config.multus %}
  multus: 
    disable: {{config.user_config.multus.disable}},
  {% endif %}
  {% if config.user_config.drop_log_config %}
  dropLogConfig:
    enable: {{ config.user_config.drop_log_config.enable }},
  {% endif %}
  {% if config.user_config.istio_config %}
  istioConfig:
    installIstio": {{ config.user_config.istio_config.install_istio}},
    installProfile": {{ config.user_config.istio_config.install_profile }},
    istioNs: {{ config.user_config.istio_config.istio_ns }},
    istioOperatorNs": {{ config.user_config.istio_config.istio_operator_ns }},
  {% endif %}

  {% if config.user_config.logging %}
  logging:
    size: {{ config.user_config.logging.size}},
    controllerLogLevel: {{ config.user_config.logging.controller_log_level }},
    hostagentLogLevel: {{ config.user_config.logging.hostagent_log_level }},
    opflexagentLogLevel: {{ config.user_config.logging.opflexagent_log_level }} 
  {% endif %}

  netConfig:
    {% if config.user_config.net_config.infra_vlan %}
    infraVlan": {{config.net_config.infra_vlan|json}},
    {% endif %}
    {% if config.user_config.net_config.service_vlan %}
    serviceVlan: {{config.net_config.service_vlan|json}}, 
    {% endif %}
    {% if config.user_config.net_config.kubeapi_vlan %}
    kubeapiVlan: {{config.net_config.kubeapi_vlan|json}},
    {% endif %}
    {% if config.user_config.net_config.extern_static %}
    externStatic: {{config.net_config.extern_static|json}},
    {% endif %}
    {% if config.user_config.net_config.extern_dynamic %}
    externDynamic: {{config.net_config.extern_dynamic|json}},
    {% endif %}
    {% if config.user_config.net_config.node_svc_subnet %}
    nodeSvcSubnet: {{config.net_config.node_svc_subnet|json}},
    {% endif %}
    {% if config.user_config.net_config.interface_mtu %}
    interfaceMtu: {{config.net_config.interface_mtu|json}},
    {% endif %}
    {% if config.user_config.interface_mtu_headroom %}
    interfaceMtuHeadroom: {{ config.user_config.interface_mtu_headroom|json }},
    {% endif %}
    {% if config.user_config.net_config.service_monitor_interval %}
    serviceMonitorInterval: {{config.net_config.service_monitor_interval|json}},
    {% endif %}
    {% if config.user_config.net_config.pbr_tracking_non_snat %}
    pbrTrackingNonSnat: {{config.net_config.pbr_tracking_non_snat|json}},
    {% endif %}
    {% if config.user_config.net_config.pod_subnet_chunk_size %}
    podSubnetChunkSize: {{config.net_config.pod_subnet_chunk_size|json}},
    {% endif %}
    {% if config.user_config.net_config.disable_wait_for_network %}
    disableWaitForNetwork: {{config.net_config.disable_wait_for_network|json}},
    {% endif %}
    {% if config.user_config.net_config.duration_wait_for_network %}
    durationWaitForNetwork: {{config.net_config.duration_wait_for_network|json}},
    {% endif %}
    nodeSubnet: {{config.net_config.node_subnet|json}}
    podSubnet": {{config.net_config.pod_subnet|json}}
    
   {% if config.user_config.kube_config %}
   kubeConfig:
    controller: {{ config.user_config.kube_config.controller }}
    useRbacApi: {{ config.user_config.kube_config.use_rbac_api }}
    useAppsApi: {{ config.user_config.kube_config.use_apps_api }}
    useAppsApigroup: {{ config.user_config.kube_config.use_apps_apigroup }}
    hostAgentOpenshiftResource: {{ config.user_config.kube_config.host_agent_openshift_resource }}
    useNetpolApigroup: {{ config.user_config.kube_config.use_netpol_apigroup }}
    useClusterRole: {{ config.user_config.kube_config.use_cluster_role }}
    imagePullPolicy: {{ config.user_config.kube_config.image_pull_policy }}
    kubectl: {{ config.user_config.kube_config.kubectl }}
    systemNamespace: {{ config.user_config.kube_config.system_namespace }}
    ovsMemoryLimit: {{ config.user_config.kube_config.ovs_memory_limit }}
    rebootOpflexWithOvs: {{ config.user_config.kube_config.reboot_opflex_with_ovs }}
    maxNodesSvcGraph: {{ config.user_config.kube_config.max_nodes_svc_graph }}
    opflexMode: {{ config.user_config.kube_config.opflex_mode }}
    hostAgentCniBinPath: {{ config.user_config.kube_config.host_agent_cni_bin_path }}
    hostAgentCniConfPath: {{ config.user_config.kube_config.host_agent_cni_conf_path }}
    generateInstallerFiles": {{ config.user_config.kube_config.generate_installer_files }}
    generateCnetFile: {{ config.user_config.kube_config.generate_cnet_file }}
    generateApicFile: {{ config.user_config.kube_config.generate_apic_file }}
    useHostNetnsVolume: {{ config.user_config.kube_config.use_host_netns_volume }}
    enableEndpointslice: {{ config.user_config.kube_config.enable_endpointslice }}
    snatOperator:
      name: {{ config.user_config.kube_config.snat_operator.name }}
      watchNamespace: {{ config.user_config.kube_config.snat_operator.watch_namespace }}
      globalinfoName: {{ config.user_config.kube_config.snat_operator.globalinfo_name }}
      rdconfigName: {{ config.user_config.kube_config.snat_operator.rdconfig_name }}
      port_range:
        start: {{ config.user_config.kube_config.snat_operator.port_range.start }}
        end: {{ config.user_config.kube_config.snat_operator.port_range.end }}
        portsPerNode: {{ config.user_config.kube_config.snat_operator.port_range.ports_per_node }}
      snatNamespace: {{ config.user_config.kube_config.snat_operator.snat_namespace }}
      contractScope": {{ config.user_config.kube_config.snat_operator.contract_scope }}
      disablePeriodicSnatGlobalInfoSync": {{ config.user_config.kube_config.snat_operator.disable_periodic_snat_global_info_sync }}
  {% endif %}
