
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-operator
  namespace: {{ config.kube_config.system_namespace }}
  labels:
    aci-containers-config-version: "{{ config.registry.configuration_version }}"
---
apiVersion: {{ config.kube_config.use_rbac_api }}
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "{{ config.registry.configuration_version }}"
    network-plugin: aci-containers
  name: aci-containers-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - nodes
  - namespaces
  - configmaps
  - secrets
  - pods
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  - limitranges
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "monitoring.coreos.com"
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - aci.ctrl
  resources:
  - acicontainersoperators
  - acicontainersoperators/status
  - acicontainersoperators/finalizers
  verbs:
  - '*'
- apiGroups:
  - aci.ctrl
  resources:
  - accprovisioninputs
  - accprovisioninputs/status
  - accprovisioninputs/finalizers
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - aci.snat
  resources:
  - snatpolicies
  - snatglobalinfos
  - rdconfigs
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - aci.snat
  resources:
  - nodeinfos
  verbs:
  - create
  - update
  - list
  - watch
  - get
{% if config.flavor == "cloud" %}
- apiGroups:
  - "aci.aw"
  resources:
  - podifs
  - podifs/status
  - gbpsstates
  - gbpsstates/status
  verbs:
  - "*"
{% endif %}
- apiGroups:
  - config.openshift.io
  - operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - update
  - list
  - watch
  - get
---
apiVersion: {{ config.kube_config.use_rbac_api }}
kind: ClusterRoleBinding
metadata:
  name: aci-containers-operator
  labels:
    aci-containers-config-version: "{{ config.registry.configuration_version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers-operator
subjects:
- kind: ServiceAccount
  name: aci-containers-operator
  namespace: {{ config.kube_config.system_namespace }}
{% if not config.chained_cni_config.secondary_interface_chaining and not config.chained_cni_config.primary_interface_chaining %}
---
apiVersion: {{ config.kube_config.use_apps_api }}
kind: Deployment
metadata:
  name: aci-containers-operator
  namespace: {{ config.kube_config.system_namespace }}
  labels:
    aci-containers-config-version: "{{ config.registry.configuration_version }}"
    name: aci-containers-operator
    network-plugin: aci-containers
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: aci-containers-operator
      network-plugin: aci-containers
  strategy:
    type: Recreate
  template:
    metadata:
      name: aci-containers-operator
      namespace: {{ config.kube_config.system_namespace }}
      labels:
        name: aci-containers-operator
        network-plugin: aci-containers
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: preferred-node
                operator: In
                values:
                - aci-containers-operator-2577247291
            weight: 1
      containers:
      {% if config.registry.use_digest %}
      - image: {{ config.registry.image_prefix }}/aci-containers-operator@sha256:{{ config.registry.aci_containers_operator_version }}
      {% else %}
      - image: {{ config.registry.image_prefix }}/aci-containers-operator:{{ config.registry.aci_containers_operator_version }}
      {% endif %}
        imagePullPolicy: {{ config.kube_config.image_pull_policy }}
        {% if config.kube_config.aci_containers_operator_memory_limit or config.kube_config.aci_containers_operator_memory_request %}
        resources:
          limits:
            {% if config.kube_config.aci_containers_operator_memory_limit %}
            memory: "{{ config.kube_config.aci_containers_operator_memory_limit }}"
            {% else %}
            memory: "{{ config.kube_config.aci_containers_memory_limit }}"
            {% endif %}
          requests:
            {% if config.kube_config.aci_containers_operator_memory_request %}
            memory: "{{ config.kube_config.aci_containers_operator_memory_request }}"
            {% else %}
            memory: "{{ config.kube_config.aci_containers_memory_request }}"
            {% endif %}
        {% endif %}
        name: aci-containers-operator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: aci-operator-config
          mountPath: /usr/local/etc/aci-containers/
        - name: acc-provision-config
          mountPath: /usr/local/etc/acc-provision/
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlibdocker
          mountPath: /var/lib/docker
          readOnly: true
        env:
        - name: SYSTEM_NAMESPACE
          value: "{{ config.kube_config.system_namespace}}"
        - name: ACC_PROVISION_FLAVOR
          value: "{{ config.flavor }}"
        - name: OPERATOR_LOGGING_LEVEL
          {% if config.logging.operator_log_level %}
          value: {{ config.logging.operator_log_level }}
          {% else %}
          value: "info"
          {% endif %}
      - env:
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ACC_PROVISION_FLAVOR
          value: "{{ config.flavor }}"
        - name: ACC_PROVISION_INPUT_CR_NAME
          value: "accprovisioninput"
        {% if config.registry.use_digest %}
        image: {{ config.registry.image_prefix }}/acc-provision-operator@sha256:{{ config.registry.acc_provision_operator_version }}
        {% else %}
        image: {{ config.registry.image_prefix }}/acc-provision-operator:{{ config.registry.acc_provision_operator_version }}
        {% endif %}
        imagePullPolicy: {{ config.kube_config.image_pull_policy }}
        {% if config.kube_config.acc_provision_operator_memory_limit or config.kube_config.acc_provision_operator_memory_request %}
        resources:
          limits:
            {% if config.kube_config.acc_provision_operator_memory_limit %}
            memory: "{{ config.kube_config.acc_provision_operator_memory_limit }}"
            {% else %}
            memory: "{{ config.kube_config.aci_containers_memory_limit }}"
            {% endif %}
          requests:
            {% if config.kube_config.acc_provision_operator_memory_request %}
            memory: "{{ config.kube_config.acc_provision_operator_memory_request }}"
            {% else %}
            memory: "{{ config.kube_config.aci_containers_memory_request }}"
            {% endif %}
        {% endif %}
        name: acc-provision-operator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aci-containers-operator
      serviceAccountName: aci-containers-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - name: aci-operator-config
        configMap:
          name: aci-operator-config
          items:
          - key: spec
            path: aci-operator.conf
      - name: acc-provision-config
        configMap:
          name: acc-provision-config
          items:
          - key: spec
            path: acc-provision-operator.conf
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
{% endif %}
