apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: null
  name: cluster
spec:
  disableMultiNetwork: true
  {% if config.flavor != "l2-tenant-chained-multus-openshift-4.12-baremetal" %}
  {% for i, subnet in config.net_config.pod_subnet|enumerate %}
  {% if is_ipv6(subnet) %}
  {% set hostPrefix = 64 %}
  {% else %}
  {% set hostPrefix = 23 %}
  {% endif %}
  {% if i == 0 %}
  clusterNetwork:
  {% endif %}
  - cidr: {{ subnet }}
    hostPrefix: {{ hostPrefix }}
  {% endfor %}
  {% endif %}
  defaultNetwork:
    type: CiscoACI
  serviceNetwork:
  - 172.30.0.0/25