# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.21/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: {{ config.calico_config.net_config.block_size }}
      cidr: {{ config.net_config.pod_subnet }}
      encapsulation: {{ config.calico_config.net_config.encapsulation }}
      natOutgoing: {{ config.calico_config.net_config.nat_outgoing }}
      nodeSelector: {{ config.calico_config.net_config.nodeSelector }}
---
# This section configures the Calico API server.
# For more information, see: https://docs.projectcalico.org/v3.21/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
{% if config.aci_config.cluster_l3out.bgp.secret %}
---
#This creates a secret to store the BGP Password. We also need to add a Role and RoleBinding to ensure the calico-node ServiceAccount can access the Secret.
apiVersion: v1
kind: Secret
metadata:
  name: bgp-secrets
  namespace: kube-system
type: Opaque
stringData:
  rr-password: {{ config.aci_config.cluster_l3out.bgp.secret }}
{% endif %}