apiVersion: netop-manager-cntrlr.netop-manager.io/v1
kind: Installer
metadata:
  namespace: netop-manager-system
  name: sample-installer
spec:
  config:
    networkFunctions:
      {% if config.service_mesh_config and config.service_mesh_topology%}
      cko-sm:
        type: cko-sm-smm
        version: "0.1"
        options:
          meshType: "Cisco-SMM"
          clusterName: {{ config.service_mesh_config.name }}
          networkName: {{ config.service_mesh_config.network }}
          meshName: {{ config.service_mesh_config.mesh_id }}
          meshMode: Active
          remoteControlPlane: 
          {% for sm_config in (config.service_mesh_topology) %}
          {% if sm_config['name'] != config.aci_config.system_id %}
          - "{{ sm_config['kubeconfig'] }}"
          {% endif %}{% endfor %}
      {% endif %}
      cko-cni:
        version: "{{ config.aci_config.cni_flavor_version }}"
        type: "cko-cni-aci"
        options:
          aci-cni: {{ config.aci_config.base64_encoded_cko_aci_spec }}
      {% if config.monitoring_config.enable %}
      cko-monitoring:
        version: '0.1'
        type: cko-m-prometheus
        options:
          prometheus-config: {{ config.aci_config.base64_encoded_prometheus_spec }}
          prometheus-node-exporter: {{ config.aci_config.base64_encoded_node_exporter_spec }}
      {% endif %}