apiVersion: netop-manager-cntrlr.netop-manager.io/v1
kind: Installer
metadata:
  name: installer-sample
  namespace: netop-manager-system
{% if config.service_mesh_config.enable or config.monitoring_config.enable %}
spec:
  config:
    networkFunctions:
      {% if config.service_mesh_config.enable %}
      cko-sm:
        type: cko-sm-smm
        version: "0.1"
        options:
          meshType: {{ config.service_mesh_config.mesh_type }}
          clusterName: {{ config.service_mesh_config.cluster_name }}
          networkName: {{ config.service_mesh_config.network_name }}
          meshName: {{ config.service_mesh_config.mesh_name }}
      {% endif %}
      {% if config.monitoring_config.enable %}
      cko-monitoring:
        version: '0.1'
        type: cko-m-prometheus
        options:
          prometheus-config: {{ config.monitoring_config.base64_encoded_prometheus_spec }}
      {% endif %}
{% endif %}