apiVersion: netop-manager-cntrlr.netop-manager.io/v1
kind: Installer
metadata:
  namespace: netop-manager-system
  name: sample-installer
spec:
  wsClient:
    serverIP: {{ config.control_cluster_websocket.server_ip }}
    targetPort: {{ config.control_cluster_websocket.target_port }}
  config:
    networkFunctions:
    {% if config.service_mesh_config.enable %}
      cko-sm:
        type: "cko-sm-smm"
        version: "0.1"
        options:
          meshType: {{ config.service_mesh_config.mesh_type }}
          clusterName: {{ config.service_mesh_config.cluster_name }}
          networkName: {{ config.service_mesh_config.network_name }}
          meshName: {{ config.service_mesh_config.mesh_name }}
    {% endif %}
      cko-cni:
        version: '0.1'
        type: "cko-cni-aci"
        options:
          aci-cni: {{ config.aci_config.base64_encoded_cko_aci_spec }}
