apiVersion: netop-manager-cntrlr.netop-manager.io/v1
kind: Installer
metadata:
  namespace: netop-manager-system
  name: sample-installer
spec:
  config:
    networkFunctions:
      {% if config.service_mesh_config and config.service_mesh_topology %}
      cko-sm:
        type: cko-sm-smm
        version: "0.1"
        options:
          meshType: "Cisco-SMM"
          clusterName: "{{ config.service_mesh_config.name }}"
          networkName: "{{ config.service_mesh_config.network }}"
          meshName: "{{ config.service_mesh_config.mesh_id }}"
          meshMode: "Active"
        arrayOptions:
          remoteControlPlane: 
          {% for sm_config in (config.service_mesh_topology) %}
          {% if sm_config['name'] != config.aci_config.system_id %}
          - "{{ sm_config['kubeconfig'] }}"
          {% endif %}{% endfor %}
      {% endif %}
      {% if config.lb_config %}
      cko-lb:
        type: "cko-lb-metallb"
        version: "0.1"
        options:
          lBType: MetalLB
        arrayOptions:
          externalCIDRs:
          - "{{ config.net_config.extern_dynamic }}"
      {% endif %}
      cko-cni:
        version: '0.1'
        type: cko-cni-calico
        options:
          calico-cr: {{ config.calico_config.base64_encoded_calico_crs_spec }}
          calico-bgp: {{ config.calico_config.base64_encoded_calico_bgp_spec }}
          calicoctl: {{ config.calico_config.base64_encoded_calicoctl_spec }}
      {% if config.monitoring_config %}
      cko-monitoring:
        version: '0.1'
        type: cko-m-prometheus
        options:
          prometheus-config: {{ config.calico_config.base64_encoded_prometheus_spec }}
          prometheus-node-exporter: {{ config.calico_config.base64_encoded_node_exporter_spec }}
      {% endif %}
