apiVersion: netop-manager-cntrlr.netop-manager.io/v1
kind: Installer
metadata:
  name: installer-sample
  namespace: netop-manager-system
spec:
  config:
    networkFunctions:
      cko-cni:
        type: cko-cni-cilium
        version: '1.11.2'
      {% if config.monitoring_config %}
      cko-monitoring:
        version: '0.1'
        type: cko-m-prometheus
        options:
          prometheus-config: {{ config.monitoring_config.base64_encoded_prometheus_spec }}
          prometheus-node-exporter: {{ config.monitoring_config.base64_encoded_node_exporter_spec }}
      {% endif %}