{% if (config.connectivity_checker or config.gitops) %}
apiVersion: controller.netop-manager.io/v1alpha1
kind: Installer
metadata:
  name: installer-platform
spec:
  operatorConfigs:
    platform:
      {% if config.connectivity_checker %}
      cko-diagnostic:
        type: "connectivity-checker"
        version: "0.1"
        options:
          01-checkerCRDs: {{ config.connectivity_checker.base64_encoded_nettools_crds }}
          02-checkerCR: {{ config.connectivity_checker.base64_encoded_nettools_crds }}
          03-errorPodsReportingCR: {{ config.connectivity_checker.base64_encoded_nettools_crds }}
      {% endif %}
      {% if config.gitops %}
      cko-gitops:
        type: "argo"
        version: "0.1"
        options:
          argo: {{ config.gitops.base64_encoded_argo_manifests }}
      {% endif %}
{% endif %}