dist: bionic
os: linux
language: python
python: 3.6
install:
  - pip install boto3
  - python provision/setup.py install
script:
  - ls
deploy:
  provider: pypi
  username: ${PYPI_USER}
  password: ${PYPI_PASS}
  server: https://test.pypi.org/index
  on:
    tags: true
