dist: jammy
os: linux
env:
  global:
    - DEFAULT_BRANCH: master
    - GOPROXY: https://proxy.golang.org,https://goproxy.io,direct
language: python
python: 3.9
jobs:
  include:
    - stage: run-unit-tests
      if: tag IS NOT present
      install:
        - pip install flake8 coverage coveralls
        - python provision/setup.py install
      script:
        - cd provision
        - coverage run --source=. -m pytest acc_provision
        - coveralls
    - stage: push-package
      if: tag IS present
      go: 1.20.x
      go_import_path: github.com/noironetworks/aci-containers
      before_script:
        - export UPSTREAM_ID=81c2369
        - eval "$(GIMME_GO_VERSION=1.20.4 gimme)"
        - export TRAVIS_GO_VERSION=1.20.4
        - export TRAVIS_GO_IMPORT_PATH=github.com/noironetworks/aci-containers
        - export TRAVIS_BUILD_USER="$(curl -s "https://api.travis-ci.com/v3/build/$TRAVIS_BUILD_ID" | jq -r .created_by.login)"
        - go version
      script:
        - echo "Skip running UTs"
        - git clone http://www.github.com/noironetworks/cicd -b main /tmp/cicd
        - pip install jq pyyaml pytz || travis_terminate 1
        - /tmp/cicd/travis/show-image-tags.sh || travis_terminate 1
        - /tmp/cicd/travis/check-git-tag.sh; RETURN_CODE=$? ; if [ $RETURN_CODE -eq 140 ]; then travis_terminate 0; elif [ $RETURN_CODE -ne 0 ]; then travis_terminate $RETURN_CODE; fi
        - python provision/setup.py install || travis_terminate 1
        - /tmp/cicd/travis/clone-aci-containers-repo.sh || travis_terminate 1
        - pushd /tmp/noironetworks/aci-containers
        - git checkout -qf ${TRAVIS_TAG}
        - /tmp/cicd/travis/show-git-repo-status.sh
        - make -C . dist-static/acikubectl || travis_terminate 1
        - popd
        - cp /tmp/noironetworks/aci-containers/dist-static/acikubectl provision/bin/acikubectl || travis_terminate 1
        - /tmp/cicd/travis/build-acc-provision.sh || travis_terminate 1
        - git add --all
        - git commit -m "Changes added by travis build"
        - pip install -U twine
        - /tmp/cicd/travis/push-to-pypi.sh
