dist: bionic
os: linux
language: python
python: 3.6
install:
  - pip install flake8 coverage coveralls boto3
  - pip3 install -U pip
  - python provision/setup.py install
script:
  - make -C provision test
  - cd provision; coverage run --source=. -m pytest acc_provision; coveralls
