apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: null
  name: cluster
spec:
  disableMultiNetwork: true
  clusterNetwork:
  - cidr: {{ config.net_config.pod_subnet|json }}
    hostPrefix: 23
  defaultNetwork:
    type: CiscoACI
  serviceNetwork:
  - 172.30.0.0/25
