apiVersion: v1
kind: ConfigMap
metadata:
  name: acc-provision-config
  namespace: {{ .Values.kubeConfig.systemNamespace | default "aci-containers-system" }}
  labels:
    {{- if (.Values.registry).configurationVersion }}
    aci-containers-config-version: {{ .Values.registry.configurationVersion }}
    {{- end }}
    network-plugin: aci-containers
data:
  spec: |-
    {
        "acc_provision_input": {
            "operator_managed_config": {
                {{- if (.Values.operatorManagedConfig).enableUpdates }}
                "enable_updates": {{ .Values.operatorManagedConfig.enableUpdates | default "False" }}
                {{- else }}
                "enable_updates": False
                {{- end }}

            },
             "aci_config": {
                 "system_id": {{ .Values.aciConfig.systemId }},
                 {{- if (.Values.aciConfig).apicHosts }}
                 "apic_hosts": {{ .Values.aciConfig.apicHosts}},
                 {{- end }}
                 {{- if (.Values.aciConfig).aep }}
                 "aep": {{ .Values.aciConfig.aep }},
                 {{- end }}
                 {{- if (.Values.aciConfig).apicSubscriptionDelay }}
                 "apic-subscription-delay": {{ .Values.aciConfig.apicSubscriptionDelay }},
                 {{- end }}
                 {{- if (.Values.aciConfig).apicRefreshtickerAdjust }}
                 "apic_refreshticker_adjust": {{ .Values.aciConfig.apicRefreshtickerAdjust }},
                 {{- end }}
                 {{- if (.Values.aciConfig).opflexDeviceDeleteTimeout }}
                 "opflex-device-delete-timeout": {{ .Values.aciConfig.opflexDeviceDeleteTimeout }},
                 {{- end }}
                 {{- if (.Values.aciConfig).tenant }}
                 "tenant": {
                  "name": {{ .Values.aciConfig.tenant.name }}
                 },
                 {{- end }}
                 "vrf": {
                  "name": {{ .Values.aciConfig.vrf.name }},
                  "tenant": {{ .Values.aciConfig.vrf.tenant }}
                 },
                 {{- if (.Values.aciConfig).syncLogin }}
                 "sync_login": {
                  {{- if .Values.aciConfig.syncLogin.username }}
                  "username": {{ .Values.aciConfig.syncLogin.username }},
                  {{- end }}
                  {{- if .Values.aciConfig.syncLogin.password }}
                  "password": {{ .Values.aciConfig.syncLogin.password }},
                  {{- end }}
                  {{- if .Values.aciConfig.syncLogin.certfile }}
                  "certfile": {{ .Values.aciConfig.certfile }},
                  {{- end }}
                  {{- if .Values.aciConfig.syncLogin.keyfile }}
                  "keyfile": {{ .Values.aciConfig.keyfile }},
                  {{- end }}
                  {{- if .Values.aciConfig.syncLogin.certReused }}
                  "cert_reused": {{ default "False" .Values.aciConfig.certReused }}
                  {{- end }}
                },
                {{- end }}
                {{- if (.Values.aciConfig).clientSsl }}
                "client_ssl": {{ default "True" .Values.aciConfig.clientSsl }},
                {{- end }}
                {{- if (.Values.aciConfig).vmmDomain }}
                "vmm_domain": {
                  {{- if (.Values.aciConfig).vmmDomain.nestedInside }}
                  "nested_inside": {
                    "installer_provisioned_lb_ip": {{ .Values.aciConfig.vmmDomain.nestedInside.installerProvisionedLbIp }}
                  }
                  {{- end }}
                },
                {{- end }}
                "l3out": {
                  "name": {{ (.Values.aciConfig).l3out.name }},
                  "external_networks": {{ (.Values.aciConfig).l3out.externalNetworks }}
                }
             },
             
         }
     }
